backend:
  name: github
  repo: XMag27/valdiviasec
  branch: main
  base_url: https://valdiviasec-oauth.larapaolos.workers.dev
  auth_endpoint: /auth

media_folder: static/images/uploads
public_folder: /images/uploads

locale: es

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - label: Título
        name: title
        widget: string
      - label: Descripción
        name: description
        widget: string
      - label: Fecha de publicación
        name: pubDate
        widget: datetime
        date_format: true
        time_format: false
        format: "MMM DD YYYY"
      - label: Fecha de actualización
        name: updatedDate
        widget: datetime
        date_format: true
        time_format: false
        format: "MMM DD YYYY"
        required: false
      - label: Imagen de portada
        name: heroImage
        widget: image
        required: false
      - label: Autor
        name: author
        widget: string
        default: "ValdiviaSec"
      - label: Tags
        name: tags
        widget: list
        default: []
      - label: Contenido
        name: body
        widget: markdown